### ISSUE TITLE
Unable to run previous project

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#1019]
Hi Keisuke,

Maybe I'm missing something, but I can't seem to get this to run.

This occurs on all three branches (master, develop, develop_v4) and also occurs in the oldest archive prepost_3.0.18.6257.

When attempting to Run the following example:
[Tutorial1.zip](https://github.com/i-RIC/prepost-gui/files/8383451/Tutorial1.zip)

Press run menu button
![image](https://user-images.githubusercontent.com/7538707/160913579-aadfd156-330f-4bc0-9529-1f7bc7df1804.png)

Press Yes
![image](https://user-images.githubusercontent.com/7538707/160914026-f77fd5f3-28fa-43a0-8958-2c8644134b84.png)

Press OK
![image](https://user-images.githubusercontent.com/7538707/160914236-6a184db0-d79c-4300-8e96-e58d2f440b73.png)

Doesn't Run

Pressing run menu button again just repeats (never runs).

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your information.

Recently, I’ve pushed several commits, to fix misc bugs, and I’m afraid
maybe I’ve pushed a commit that cause the issue you reported. I’ll look
into it soon.

Thank you,

Keisuke


2022年3月31日(木) 4:39 Scott Charlton ***@***.***>:

**Comment by kskinoue0612** [comment]
Hi Scott,

I've tested with the project file you've registered. I've got the same result.
I've noticed that the project has no grid data, so imagined maybe that caused the odd behavior.
I've created a grid, saved to project, then, solver run.

Can you make sure, please?

Thank you,

Keisuke

**Comment by kskinoue0612** [comment]
> I did notice that iRIC_v4 crashes when opening the [ex3.zip](https://github.com/i-RIC/prepost-gui/files/8393189/ex3.zip) project that was run in either iRIC(master) or iRIC(develop).
> 
> It crashes on this line:
> 
> https://github.com/i-RIC/prepost-gui/blob/e8bef263b63b9536e6014427f8684b9b43ba1401/libs/guicore/misc/cgnsutil.cpp#L21
> 
> sol is NULL.
> 
> Thanks, Scott

Hi Scott,

Today I've worked on it, and fixed it. it was a bug of iriclib.
I've registered the issue as a separate issue, and sent a pull request to close it.

https://github.com/i-RIC/iriclib_v4/pull/33

Thank you,

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

> Didn't it used to tell you when there was no grid defined?

Yes, before running the solver, iRIC notices when there is no grid. But in case there is no grid and there are edited geographic data, it does not. I agree that it is confusing.

I've pushed a pull request to fix it.
https://github.com/i-RIC/prepost-gui/pull/1021

Not in a hurry, when you have time, please check the pull request.

Thank you,

Keisuke
