### ISSUE TITLE
iRIC 2.3 saving *.ipro file fails when the number of files is too big

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#11]
When the number of files users are going to save in *.ipro file is too big (more than 1000), creating 
archive file fails, because of limitation of zip.exe

The GUI should check the number of files to save, and show warning to ask user to save as folder,
when the number of files is too big.

**Comment by kazutake** [comment]
Can the iRIC show those warning messages when those cases occur? Please implement it.

**Comment by kskinoue0612** [comment]
You can check with the following procedure:
1. Start a new project.
1. Import the shape file I attach.
1. Try to save the project as *.ipro file. 
[shape_for_11.zip](https://github.com/i-RIC/prepost-gui/files/558369/shape_for_11.zip)

**Comment by kazutake** [comment]
OK. But it is very late to show its message I think. How did you show the message?

**Comment by kskinoue0612** [comment]
The message is shown after generating the list of files to save, and counting the number of files.
I guess generating the list takes time.
