### ISSUE TITLE
グラデーションモードのカラーマップの凡例の改善

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1112]
現在は、凡例には、色が定義された値とそこでの色に基づいて凡例が表示される。

この機能を拡張し、最大値、最小値の間の分割数を指定し、色が定義されていない位置にも数字を表示できる機能を追加する。

**Comment by starfieldKt** [comment]
da6f22caa92d80a83c4c74a3c8e3f4df615f0278 にて改善済みを確認

![image](https://user-images.githubusercontent.com/106499621/225815892-c6e1c281-64b5-44dd-b752-b9e4348d563d.png)
