### ISSUE TITLE
カラーマップ設定機能の改善

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1113]
* 一番下の色も消せるようにする。
* 複数行をまとめて削除できるようにする。
* 区間別モードに切り替える際、全体での分割数を指定できるようにする。レインボーカラーの時に便利。
* グラデーションモードで、凡例に表示する色の数を指定できるようにする。

**Comment by starfieldKt** [comment]
一番上も同様に消せないので対応願います。
> * 一番下の色も消せるようにする。

**Comment by starfieldKt** [comment]
c835948c2f19974c9fbb36ed5913641cb88f1ad8
以下の改善を確認
>* 区間別モードに切り替える際、全体での分割数を指定できるようにする。レインボーカラーの時に便利。

64c4f6c58bf03a3c4871a2541074ea6d90508945
以下の改善を確認
>* 一番下の色も消せるようにする。
>* 複数行をまとめて削除できるようにする。
>* 一番上も同様に消せないので対応願います。

da6f22caa92d80a83c4c74a3c8e3f4df615f0278
以下の改善を確認 ( #1112 と重複)
>* グラデーションモードで、凡例に表示する色の数を指定できるようにする。
