### ISSUE TITLE
メインウィンドウのiRICのロゴを移動可能にする。

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1123]
* メインウィンドウの右下に表示されているiRICのロゴを移動可能にする。
* イメージとしては以下のようにオブジェクトブラウザにロゴの項目を追加し選択した状態でドラッグによる移動、プロパティによる位置の指定ができると便利
* ロゴの種類も選べると便利かもしれない
* 非表示にはできないようにする。

![image](https://user-images.githubusercontent.com/106499621/227104004-ead5296b-0945-4091-a3ff-41fd695572bc.png)

**Comment by kazutake** [comment]
ok
