### ISSUE TITLE
ラベル機能で設定できる書式の拡張

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1129]
ラベル機能で以下の機能を追加する。
* ギリシャ文字を使用。
* 上付き、下付き文字を設定。m<sup>3</sup>/s

**Comment by kazutake** [comment]
オブジェクトブラウザーのcaptionでギリシャ文字等のUnicode文字を使用できるようにする #1311 と同じ

**Comment by kazutake** [comment]
オブジェクトブラウザーのcaptionでギリシャ文字等のUnicode文字を使用できるようにする #1311
