### ISSUE TITLE
カラーマップの凡例表示機能の改善

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1147]
カラーマップの凡例は、以下の3つから選択できる。
* 選択しているときのみ表示
* 常に表示
* 常に非表示

しかし、「選択しているときのみ表示」はわかりにくいので、「表示」チェックボックスのみにしてシンプルにする。
また、凡例の表示・非表示の切り替えが簡単になるよう、地理情報グループを選択している時、ツールバーに凡例の表示・非表示切り替え用のチェックボックスを表示する。

**Comment by starfieldKt** [comment]
地理情報を選択した際にツールバーにアイコンは追加されるが、表示・非表示の切り替えではなくプロパティ画面を開く機能になっている。

![image](https://user-images.githubusercontent.com/106499621/233876678-734ea55c-20c3-499a-b5d3-3b1f0e3934db.png)

**Comment by starfieldKt** [comment]
地理情報等、半透明の項目がある項目も選択した際にツールバーに半透明の設定項目を追加してもよいのではないでしょうか。
![image](https://github.com/i-RIC/prepost-gui/assets/106499621/a6ac68e1-28c9-40e0-91fd-430f4acf92fb)
