### ISSUE TITLE
二次元可視化ウィンドウにも、カラーバーの表示・非表示機能をつける

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1150]
二次元可視化ウィンドウのツールバーにもカラーバーの表示・非表示機能をつける。地理情報と計算結果両方に対応。

**Comment by starfieldKt** [comment]
二次元可視化ウィンドウでの対応は確認。

二次元鳥観図ウィンドウや三次元可視化ウィンドウでの対応もあるとよいと思われます。

**Comment by kskinoue0612** [comment]
コメントありがとうございました。
先程、v4 (develop版) を更新しました。 12:00 過ぎには Online Update で入手し、ご確認いただけるようになると思います。最新の v4 (develop版) では、二次元鳥瞰図ウィンドウ、三次元可視化ウィンドウも対応済みとなっています。ご確認下さい。

## 二次元鳥瞰図ウィンドウ スカラー

![2dbirdeye_contour](https://github.com/i-RIC/prepost-gui/assets/4031569/54a3d2b7-ff63-4392-b45e-b612e0c72d6f)

## 三次元可視化ウィンドウ コンター

![3d_contour](https://github.com/i-RIC/prepost-gui/assets/4031569/68291b98-c4ff-4b47-be02-3f4cc702df0d)

## 三次元可視化ウィンドウ 矢印

![3d_arrows](https://github.com/i-RIC/prepost-gui/assets/4031569/fcdb6270-5c0b-4f30-9219-19258708e921)

**Comment by starfieldKt** [comment]
確認しました。
