### ISSUE TITLE
格子横断図ウィンドウで縦断図を開ける

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#1159]
上下流の表示がleftbnak rightbankとなっている

**Comment by starfieldKt** [comment]
iRIC v4 dev 4.0.0.6963にて表記の修正を確認

**Comment by starfieldKt** [comment]
ウィンドウの名前が縦断方向でも横断方向でも「格子横断図ウィンドウ」なのは縦断図を表示している時に誤解を与えるのではないでしょうか？

また、縦断表記の際にLeft Bank Side, Right Bank SideをDownstream, Upstreamに修正したが、表示するかしないかのチェックボックスの名称が「左右岸」のままになっている。

![image](https://github.com/i-RIC/prepost-gui/assets/106499621/da6c36d0-6aa3-4e66-be39-2a43dad5e6dc)
