### ISSUE TITLE
複数の断面でのグラフのスクリーンショット、CSVの一括エクスポート機能

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1169]
iRIC には、I 方向、J方向のグラフについてはスクリーンショット、CSVの一括エクスポート機能があるが、参照情報に追加・インポートした折れ線に沿ったグラフについてはその機能がない。

格子は河川横断データの断面位置とは無関係に切るが、河川横断線の位置での断面グラフをエクスポートしたいというケースが有り、そのような場合には上記機能があると便利なので追加してほしい。

**Comment by kazutake** [comment]
ok
