### ISSUE TITLE
計算条件などのヒント情報表示機能の追加

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1173]
ソルバ定義ファイルに、ヒント情報を追記する機能を追加する。
ヒント情報があった場合は、ダイアログに 「？」マークのアイコンが表示され、そのアイコンの上にマウスが来るとポップアップでヒント情報が表示される。

**Comment by starfieldKt** [comment]
HTMLタグ、文字参照、Unicode文字、改行など諸々も使える。
