### ISSUE TITLE
スカラーを表示していないのに凡例が表示される。

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1185]
環境
iRIC v4 dev 4.0.0.6957
iRIC v4 4.0.0.6902

症状
・プリポスト画面で`格子点の属性`、`セルの属性`の凡例を表示後、オブジェクトブラウザーでスカラーの表示のチェックボックスを外しても凡例の表示が消えない。
・可視化ウィンドウではスカラーのチェックが入っていなくてもツールバーに凡例の表示と縦横の切り替えメニューが出てくるが、プリでは出てこない。

![image](https://github.com/i-RIC/prepost-gui/assets/106499621/a7d15c74-c5ba-4838-abe4-8713947aa49a)

**Comment by kskinoue0612** [comment]
カラーバーの表示のロジックについて全体的にWeb会議で議論・整理してから反映する

**Comment by starfieldKt** [comment]
issueの内容は解消しているのでclose

**Comment by starfieldKt** [comment]
三次元可視化ウィンドウでコンターを追加した際に、面が追加されていないor表示されていない状況でも凡例が表示されています。ベクトルも同様です。
![image](https://github.com/i-RIC/prepost-gui/assets/106499621/8b366f8d-021d-4be4-880e-14a1529defe8)

**Comment by starfieldKt** [comment]
コンター面を追加して削除してもカラーバーが消えない

https://github.com/i-RIC/prepost-gui/assets/106499621/3daa2e64-664c-47da-bd61-370a61f53b83
