### ISSUE TITLE
iRICでの複数ケース自動実行ツールの開発

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1191]
iRICで、計算条件を変えた複数のプロジェクトを自動生成し、実行するツールを開発する。
流量、粗度係数などの条件を別途指定して、例えば流量 x 5, 粗度係数 x 5 なら 25個のプロジェクトを自動生成する。
また、計算結果から、例えば各プロジェクトでの最高水位を抽出して、CSVにまとめて書き込めるようにする。
これにより、iRIC を以下のワークフローに活用しやすくする。

1. データ集める
2. データ編集する
3. 計算する
4. 分析する（AIの余地あり）
5. 問題解決または意思決定に必要なデータを作成する

**Comment by kazutake** [comment]
ok
