### ISSUE TITLE
計算結果を 分割して複数の CGNS ファイルに出力する機能を有効化すると、3次元の計算結果を含むソルバで異常終了する。

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1193]
NaysCUBE など 3次元の計算結果を含むソルバのプロジェクトで、複数のCGNSファイルに計算結果を分割して出力する機能を有効化すると、計算結果の読み込み時に異常終了する。

**Comment by starfieldKt** [comment]
iRIC v4 dev 4.0.0.6963にてクラッシュしないことを確認
