### ISSUE TITLE
横断測量データインポート時にデータが存在しないと異常終了する

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1194]
国土交通省 横断測量データのインポート時に、断面一覧のcsvを選択後、一覧に記載のある断面が１つも存在しないフォルダを選択してインポートを実行すると異常終了する。

**Comment by starfieldKt** [comment]
iRIC v4 dev 4.0.0.6963にて修正を確認

**Comment by starfieldKt** [comment]
iRIC v4 dev 4.0.0.6992で確認
再発しています。

**Comment by kskinoue0612** [comment]
星野さんから 11/21 17:16 に iRIC v4 bug report のチャットで、異常終了するデータを共有いただいた

**Comment by starfieldKt** [comment]
横断測線の平面位置データ選択後、選択したフォルダ内に横断面形状データと異なるフォーマットのデータがあった場合に異常終了していた。
iRIC develop版 4.0.0.6998にて修正を確認
