### ISSUE TITLE
カラーバーのまとめて設定機能がほしい

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1196]
以下のような項目をまとめて設定できるようにする。
* フォント
* サイズ
* 文字色
* 背景色

そのうえで、位置 (例: 左上・右上など) だけは、カラーバーごとに自動的に別の値を指定する。
例えばデフォルトだと右上・右下・左下・左上とか。
そうすると、簡単に揃った感じの表示にできる。位置はダイアログで手動で指定もできるとよい。

**Comment by kazutake** [comment]
ok
