### ISSUE TITLE
横断図・縦断図ウィンドウで格子属性を編集できるようにする。

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1209]
馬場さまからのご連絡、

> 先日の幹事会でチャットで書いたのは、V3では出来ていた計算グリッドの標高の修正方法（横断図または縦断図の中で、一つあるいは複数の点を選んでマウスで上下にドラッグするだけ）が、V4では出来ないのですが、僕だけでしょうか？

v4でもv3と同様に横断図・縦断図ウィンドウから格子・セル属性を編集できるようにする。
![image_3](https://github.com/i-RIC/prepost-gui/assets/106499621/408244e6-3bb9-4180-9d5f-fb0992bd7270)

**Comment by kskinoue0612** [comment]
表形式での編集と、マウスドラッグでの編集の両方に対応する。
