### ISSUE TITLE
PCにiRIC v4をインストール時に*.iproが関連付けされない。

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1219]
iRIC v3がインストールされていないPCにiRIC v4をインストールすると*.iproが関連付けされない。

既定のアプリを`iRIC.exe`にすると*.iproをクリックで起動はできるがアイコンがiRICのアイコンになる。

iRICv4が正式にリリースされたのでv3がインストールされていてもインストール時にv4を関連付けできるか選択できるようにしてはどうか？（ただしv3を開くときにもv4で開かれるので保存するとv3で開けなくなる旨の注意書きは必要か。）

**Comment by kskinoue0612** [comment]
インストーラの更新で解消
