### ISSUE TITLE
複数のソルバの計算結果をまとめて一つの CGNS ファイルに出力するツール

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1231]
iRIC-MI を使って計算をした場合、ソルバの計算結果は、ソルバごとにそれぞれ異なる CGNS ファイルに出力される。しかし、可視化する時は複数のソルバの計算結果を、同じ画面で表示したい時がある。

これに対応するため、複数の CGNS ファイルの計算結果を読み込み、1つのCGNS ファイルに出力するツールを開発する。
本ツールでは以下を考慮する。

## 時刻の処理

ソルバごとに、delta T が異なることが iRIC-MI ではありえる。

例えば、ソルバ A, ソルバ B が以下の時刻に計算結果を出力するケースを考える。

* ソルバ A: 0, 5, 10, 15, 20
* ソルバ B: 0, 4, 8, 12, 16, 20

このようなケースに対応するため、本ツールでは、時刻について以下から選択できるようにする。

###  全ソルバの時刻をマージして時刻のリストを作る

上記で示した例では、マージ後の CGNS ファイルの時刻は 0, 4, 5, 8, 10, 12, 15, 16, 20, ... となる。

この方法のメリット、デメリットは以下の通り。

* メリット: 各ソルバでの値の変化点がすべて正しく可視化できる
* デメリット:  マージ後の計算結果では、計算結果ごとの 時刻の差分が時刻によって異なることになってしまう (例: 0 -> 4 では dt = 4, 4 -> 5 では dt = 1)。 これは動画を作る際には不都合である。

### マージ後の CGNS ファイルでの Delta T を指定する。

例えば、 Delta T を 10 と指定する。すると、t = 0, 10, 20, ... での計算結果が保存される。

* ソルバ A: 0, 10, 20, ... での計算結果がそのまま出力される。
* ソルバ B: 例えば t = 10 の計算結果はないため、t = 8 の時点での計算結果を t = 10 の結果として出力する。t = 20 については t = 20 の計算結果があるのでそれを出力する。

## 座標系の処理

ソルバごとに座標系が異なることが iRIC-MI ではありえる。
その場合、出力する CGNS ファイルの座標系を指定することで、マージする際に座標系の変換も自動的に行い、マージ後のCGNS ファイルの計算結果は全て共通の座標系となるようにする。

**Comment by kazutake** [comment]
ok
