### ISSUE TITLE
Google Maps を、背景画像(インターネット) のデフォルト設定から削除する

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1237]
Google Maps は、Google Map API のアップデートで iRIC で動かなくなったので、デフォルト設定から削除する。

**Comment by starfieldKt** [comment]
消えている事を確認。

代わりにタイルのURLを追加する。
 #1243

**Comment by starfieldKt** [comment]
「Google Map APIキーの入力」ボタンももう不要なので消してもよいと思います。
