### ISSUE TITLE
点群データの操作を取り消すとTINの自動生成が動作しない

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1278]
# 環境
iRIC v4 develop版 4.1.0.7031

# 状況
点群データの点を削除してTIN編集モードに移行するとTINが自動で再生成される。ここで操作の取り消し（Ctrl+Z)で消した点を復活させるとTINの自動生成がされなくなる。
マッピング時のTIN自動生成もしないので実際の点群とTIN間で違いが生じている。

https://github.com/i-RIC/prepost-gui/assets/106499621/bff156ce-dead-4727-af55-431ec79d2296

**Comment by kskinoue0612** [comment]
TIN の再生成という操作は本来アンドゥができない操作なのに、できる状態になっているのが問題。TIN 編集モードへの移行も含め、TIN の再生性が行われたタイミングで、それまでの操作がアンドゥできないようにする。
