### ISSUE TITLE
v4 (Release)版 二次元可視化ウィンドウの設定内容が、v4 (Develop版)でプロジェクトを開いた時に正しく復元されない

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1290]
3次元可視化ウィンドウのベクトルの面設定が正しく復元されない
3dVelocity のフォルダが増えている

**Comment by starfieldKt** [comment]
二次元可視化ウィンドウのベクトルがrelease版で保存したものをdev版で開くと消える

**Comment by starfieldKt** [comment]
二次元可視化ウィンドウのベクトルが複数ある場合release版で保存したものをdev版で開くと1つしか表示されない

**Comment by starfieldKt** [comment]
Particle（画像）のサイズなどの設定がRelease版で開いて保存すると消える

**Comment by starfieldKt** [comment]
Release版が更新されれば治るはずなので一度close
