### ISSUE TITLE
格子横断ウィンドウを開いた状態でプロジェクトを保存すると、プロジェクトを開こうとした時に異常終了する (v4)

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1294]

**Comment by starfieldKt** [comment]
異常終了はしなくなったが、エラーが表示される。
![image](https://github.com/i-RIC/prepost-gui/assets/106499621/a6e981c0-5ce1-4b0c-9b16-ef6027d203f2)

格子横断ウィンドウは開いたままにはなっているが、positionのスライドバーが消え、本来選択できない`0`が選択されている。
![image](https://github.com/i-RIC/prepost-gui/assets/106499621/89afdf07-bcd6-4b88-8b9b-3420f15c90f1)

**Comment by starfieldKt** [comment]
release版6924、dev版7024で共に修正を確認
