### ISSUE TITLE
辞書ファイルの修正

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1310]
-  粒子（画像）のプロパティダイアログ

    - "線の太さ"→”幅”

**Comment by starfieldKt** [comment]
* ポストプロセッサーのオブジェクトブラウザー`Edge (I-direction) attributes`、`Edge (J-direction) attributes`
![image](https://github.com/i-RIC/prepost-gui/assets/106499621/3446f5c1-7612-423b-9617-99537f93ed0a)

**Comment by starfieldKt** [comment]
パーティクルの日本語訳の統一

現在
| 種類 | 日本語表記 |
| :-- | :-- |
| iRIC GUIで表示されるパーティクル | パーティクル(自動) |
| Write_Sol_Particle | 粒子 |
| Write_Sol_ParticleGroup | 粒子 |
| Write_Sol_ParticleGroupImage | 粒子(画像) |

**Comment by kskinoue0612** [comment]
星野さんがコメントしてくださった「パーティクルの日本語訳の統一」は未対応のため Reopen した

**Comment by starfieldKt** [comment]
「粒子」を「パーティクル」に変更して統一する方針に決定

**Comment by starfieldKt** [comment]
「パーティクル」に変更されていることを確認
![image](https://github.com/i-RIC/prepost-gui/assets/106499621/d59f6b88-ff4a-4048-9160-8646755f6d29)

**Comment by starfieldKt** [comment]
* 距離計測ツールのプロパティが英語になった。
* iricDistancemeasure_ja_JP.qmは入っている

![image](https://github.com/user-attachments/assets/8949b113-a1d0-413a-8588-349c7ea9682c)
