### ISSUE TITLE
ユーザが設定を追記したソルバ定義ファイルを読み込めるようにする

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1314]
definition.xml はソルバー開発者が準備するが、ユーザが、特定のソルバを使う時に、計算結果でデフォルトで使うカラーマップなどを変更したい場合がある。そういう時、例えば definition_user.xml などの名前でファイルを保存するとそちらを読むようにすることで、計算条件、カラーマップなどのデフォルト値を変更でき、プロジェクトを作成する際の利便性を高めることができる。

**Comment by kazutake** [comment]
これはまだ声が少ないので一旦クローズします
