### ISSUE TITLE
Case1_input.cgn に関する仕様を iRIC 4.0 の状態に戻す

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1353]
Case1.cgn を軸とし、 Case1_input.cgn などはそのバックアップとするという方針とする。

iRIC 4.1 では仕様を変更し、以下のようにしてある。これが混乱の原因になっているので、戻す。
戻す修正が簡単に行えるか、 Git のログを確認する。

## 変更前

- プロジェクトを保存する時:
    - 格子が編集・削除されていた時 → Case1.cgn を新規作成して計算条件、計算格子を保存
    - 格子が編集・削除されていなかった時 → Case1.cgn 編集モードで開き、計算条件だけ更新して保存
- プロジェクトを開く時:
    - Case1.cgn から読み込んだ格子をプリプロセッサに表示
    - Case1.cgn から読み込んだ格子と計算結果を可視化ウィンドウに表示
    - ※ もしソルバの異常終了などで Case1.cgn が壊れていた時は Case1_input.cgn を探し、もしあれば Case1.cgn にコピーしてそちらから読み込む。
- ソルバ実行時
    1. プロジェクトを保存する時と同じ処理をして Case1.cgn を最新の状態にする
    2. Case1.cgn を Case1_input.cgn にコピー
    3. ソルバを起動して Case1.cgn を渡す

## 変更後

- プロジェクトを保存する時:
    - Case1_input.cgn を新規作成して計算条件、計算格子を保存
- プロジェクトを開く時:
    - Case1_input.cgn から読み込んだ格子をプリプロセッサに表示
        - ※ Case1_input.cgn がなかった場合 (v3 のプロジェクトを開いた場合など) は、 Case1.cgn から読み込む
    - Case1.cgn から読み込んだ格子と計算結果を可視化ウィンドウに表示
- ソルバ実行時
    1. プロジェクトを保存する時と同じ処理をして  Case1_input.cgn を最新の状態にする
    2. Case1_input.cgn を Case1.cgn にコピー
    3. ソルバを起動して Case1.cgn を渡す

**Comment by kskinoue0612** [comment]
上記を実施するとともに、プロジェクトフォルダを保存せずに閉じた時、確実に、プロジェクトを開いた時と同じ状態で次回も開けるようにするため、以下の変更を行う。

* プロジェクトを閉じた時は、project.xml, input1.cgn を含め、ファイルの上書き保存を一切行わない。
* project.xml と実データの不整合が起きないようにするため、地理情報などを削除した場合も実データの削除は行わず、メモリ上から消すだけでファイルは残したままにする。削除された地理情報の実体のファイルは、プロジェクトフォルダを保存した時に初めて削除するようにする。

**Comment by kazutake** [comment]
★Case1..cgnやproject.xmlのデータを更新するタイミングはユーザのアクションとする

・case1.cgnをベースにする
・case1_input.cgnはバックアップとしてのみ作成、利用。作成タイミングは計算実行時のみ。
・計算結果等がある場合に、保存しないで閉じた場合は、画面上の状態を一切保存しない
・地理空間データは、ユーザー操作によって削除されても物理的にはデータを残す。
・ユーザーが保存ボタンをクリックしたときに、画面状態とデータの保存、削除を行う
・計算実行ボタンをクリックしたときに表出するメッセージを以下にする

------------------------------------------------------------------------
計算実行にあたり以下を確認してください。

　・既存の計算結果がある場合は削除されます
　・現在、画面上で確認できる計算条件、計算格子がCase1.cgnに格納されます
　・ソルバーはCase1.cgnからそれらデータを読み込み計算を実行します

　よろしいですか？

Yes  No
------------------------------------------------------------------------

**Comment by kskinoue0612** [comment]
> 地理情報を消す際の処理は問題いと思いますが、地理情報を追加した場合だとproject.xml には載っていないがフォルダに格納されたデータとして残ってしまいませんか？

上記、ご指摘のとおりです。ただ、対策は打ってあります。

以下のようになります。

1. プロジェクトを新規作成し、プロジェクトフォルダに保存する
2. 地理情報を追加する -> 地理情報を格納したファイルがフォルダにできる
3. プロジェクトを保存せずに閉じる -> 2. でできたファイルが残る
4. 上記プロジェクトを開く
5．プロジェクトを保存する -> 2. でできた、project.xml に乗っていないデータは、このタイミングで削除される

なので、ずっとゴミデータが残ってしまうということはありません。プロジェクトの保存のタイミングできれいになります。
