### ISSUE TITLE
計算結果の読み込みでの異常終了への対応

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1375]
以下の issue に関連。iriclib で、計算結果の読み込みができなかった時、異常終了しないようにする。

https://github.com/i-RIC/iriclib/issues/94

**Comment by starfieldKt** [comment]
開けるようになったが、GELATOのパーティクルを表示した状態でアニメーションを最後のコマを表示しようとすると落ちる。

**Comment by starfieldKt** [comment]
* dev版と同じソースを手元の環境でビルドすると、DebugモードでもReleaseモードでも異常終了が発生しないという状態
* AppVeyorで自動ビルドされるとバグが発生する。
* 原因究明中

**Comment by kskinoue0612** [comment]
デフォルトで一つ距離計測ができるのをやめる。デフォルトで一つ作るのが、Q400_Gelato のプロジェクトの読み込みで異常終了する原因になっていたし、必要ないので。

**Comment by kskinoue0612** [comment]
doLoadFromProjecMainfile() で clearChildItems() をしているところで、は、 updateItemMap() を必ず呼び出すようにする。

**Comment by starfieldKt** [comment]
異常終了はしなくなったのは確認

**Comment by starfieldKt** [comment]
40b684bcf1450bfca8014d8e427a6ec21d423ead で以下の修正も確認

> doLoadFromProjecMainfile() で clearChildItems() をしているところで、は、 updateItemMap() を必ず呼び出すようにする。
