### ISSUE TITLE
流向チェック機能で無限ループに陥る

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1385]
以下のデータで、流向チェック機能が無限ループに陥るかチェックし、陥るようであれば不具合として修正する。

https://river-link.co.jp/share/2406/mizunami_10.zip

流末の値0がないと無限ループになる？

**Comment by starfieldKt** [comment]
by @kazutake 
上記確認しました。
「向きの不正なセルの確認」。チェックはうまく行えていることを確認しました。
リストをクリックすると、その場所に移動できる機能は必要ですが、
確認後、自動的に不正な場所にフォーカスする機能は不要です。

→　自動フォーカス機能をoffにしてリリース版に反映してください

**Comment by kskinoue0612** [comment]
> 上記確認しました。
> 「向きの不正なセルの確認」。チェックはうまく行えていることを確認しました。
> リストをクリックすると、その場所に移動できる機能は必要ですが、
> 確認後、自動的に不正な場所にフォーカスする機能は不要です。
> 
> →　自動フォーカス機能をoffにしてリリース版に反映してください

上記を対応の上、Dev版、Release版に反映しました。
