### ISSUE TITLE
Add "Force stop solver" function

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#139]
When the solver create ".cancel_ok" file by calling 

`call iric_initoption_f(IRIC_OPTION_CANCEL, ier)`

When user clicks "STOP" button, iRIC GUI do not terminate the solver process, but create ".cancel" file, and wait until the solver stops.

But if something wrong occurs in solver (like infinite loop), solver do not recognize that the ".cancel" file is created, and do not stop. In such cases there is no way to force solver to stop.

To avoid such cases, we should add way to force solver to stop.

Maybe we add "Force stop" button, or the GUI waits for 30 seconds (for example), and if the solver do not stop, iRIC GUI shows a dialog and ask user to terminate the solver process.

**Comment by kskinoue0612** [comment]
You can use the attached solver "neverend" to test this issue.
This solver creates ".cancel_ok", and never end.

[neverend.zip](https://github.com/i-RIC/prepost-gui/files/1370919/neverend.zip)

**Comment by scharlton2** [comment]
Hi Keisuke,

I was looking at the source code for fastmech and found a call to:

    iric_initoption_f(IRIC_OPTION_CANCEL, ier)

but I didn't find any calls to:

    iric_check_cancel_f(canceled)

Should it be calling iric_check_cancel and exiting the solver if 
canceled is .TRUE.?

I also noticed that if I manually kill fastmech (with windows task manager) while
the '30 seconds have passed...'  is displayed and answering 'Yes' crashes iRIC.

I couldn't get the '30 seconds have passed...' dialog in debug mode so I don't know
what caused the crash. I think it's never returning from 'processEvents'.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Generally speaking, if the solver calls,
```
iric_initoption_f(IRIC_OPTION_CANCEL, ier)
```

it should do the following.
```
iric_check_cancel_f(canceled)
if (cancel ==1)
  stop
endif
```
Please fix FaSTMECH in that way.

Honestly, I think the topic will not be a big issue for FaSTMECH, because FaSTMECH runs so fast,
and it finishes calculation before user can push stop button in most cases.

> I also noticed that if I manually kill fastmech (with windows task manager) while
> the '30 seconds have passed...' is displayed and answering 'Yes' crashes iRIC.

Thank you for your information. I'll check, and fix this issue.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I think I've fixed the issue you've found on the pull request #167 . Please check.

Thanks,
Keisuke
