### ISSUE TITLE
iRIC 2.3 geographic data naming bug

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#14]
When use follows the procedure below, an issue occur:

1. Start a project with iRIC 2.3.8 or earlier
1. Import polygon from ESRI Shape file.
1. Use move up/down to change the orders of polygons
1. Save as *.ipro file
1. Load the project file. "Polygon 3" (for example) is lacking, because of the bug
   that existed in iRIC 2.3.8.
1. Delete all geographic data
1. Import ESRI Shape file

Imported polygons are named like "Polygon 1", "Polygon 2", "Polygon 4", because "Polygon 3" already
exists (even it is not visible).

**Comment by kazutake** [comment]
I cannot understand. ???

**Comment by kskinoue0612** [comment]
You can reproduce the bug with the following procedure:

1. You need khendo2dx solver. Pleases copy khendo2dx folder to the solver folder, if you do not have it.
1. Open project.ipro
1. Delete all the polygons under "マニング粗度係数" group
1. Import polygons.shp into "マニング粗度係数". Name is with setting "Name is set automatically (ex. Polygon1)". Value is loaded from Shape file attribute "Value".

  When you use iRIC 2.3.10 or earlier, "Polygon7" does not exist. When you use iRIC 2.3.11.6405, "Polygon7" exists.
[data_for_14.zip](https://github.com/i-RIC/prepost-gui/files/558372/data_for_14.zip)

**Comment by kazutake** [comment]
OK. I confirmed above.
