### ISSUE TITLE
「長い辺を持つ三角形の削除の有効化」機能で閾値より小さい辺も削除される

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1406]
dev 4.1.0.6936で確認

画像のとおり明らかに閾値以下の三角形まで削除対象になっている。
![image](https://github.com/user-attachments/assets/6ad9e60e-5a61-46ef-83d1-5771868800f2)

**Comment by kskinoue0612** [comment]
再現しなかった。

[issue-1406.zip](https://github.com/user-attachments/files/16407903/issue-1406.zip)
![issue-1406](https://github.com/user-attachments/assets/5dac4876-b177-470b-bb2f-4b89a51dcc7c)

**Comment by starfieldKt** [comment]
発生するプロジェクト
[20240726_koushijyouken.zip](https://github.com/user-attachments/files/16407964/20240726_koushijyouken.zip)
