### ISSUE TITLE
正常に開けない可視化ウィンドウの設定があると、プロジェクトを開いた時にiRICが異常終了する

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1412]
XMLファイルが壊れているなどの理由で開けない可視化ウィンドウがあった時、iRIC が異常終了する。

7/25 16:28 旭氏より提供されたデータ 「検証モデル1_240717.ipro」で発生。

**Comment by starfieldKt** [comment]
ソルバーがある場合は問題なく開けるが、post onlyだと異常終了して開けない

**Comment by starfieldKt** [comment]
原因は正常に開けないウィンドウは削除する機能が正常に動いていなかった。具体的にはウィンドウを削除する前にウィンドウの情報(ウィンドウサイズ)を読み込んでしまっていた。

セル中心、エッジのグラフウィンドウが正確に開けないウィンドウだった。
https://github.com/i-RIC/prepost-gui/issues/1423
