### ISSUE TITLE
壊れたCGNSを読み込んだ瞬間にiRICが落ちるので分割設定やバックアップが機能していない

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1429]
cgnsファイルが壊れている際の対応は既によういされているが、壊れたcgnsを読んだ瞬間に落ちるので機能していないので調査と例外処理を網羅する。

一度正常に読み込めるかの調査をするなどの処理をいれるのはどうか？

**Comment by kskinoue0612** [comment]
調査対応内容を以下に記録する。

# ソルバがCGNSファイルを壊して終了するパターンの再現

debug_solver の最後に以下のコードを追加し、最後の計算結果の CGNS ファイルを壊すようにした。

```python

# 分割保存の場合、最後の計算結果を壊す
with open('result/Solution' + str(time_end + 1) + '.cgn', 'w') as f:
    f.write('broken')
```

試した結果、以下のようになった。

- 画面上に、以下のメッセージが出る。
    
![screenshot](https://github.com/user-attachments/assets/9f1ff859-d8b4-4950-817a-a55fd03f6f4c)
    
- 壊れていた result/Solution101.cgn は、iRIC GUI によって削除される

結果的に、iRIC は異常終了しなかった。

# その他のCGNSファイルを壊すパターンの試行

以下のパターンを試した。

1. ソルバは全タイムステップの計算結果を正常に出力
2. GUI が、全 CGNS ファイルを開く/閉じるを繰り返し、全ファイル正常に読めることを確認、時刻の一覧を生成する
3. その後で、ファイルを壊す (例: result/Solution2.cgn)
4. タイムスライダーを移動し、該当する計算結果を可視化させる

このパターンだと異常終了した。

そこで、ソルバの実行が完了後のチェックでは一度正常に読めていたファイルについても、ファイルを開くときに都度チェックし、ファイルが開けなかったらの警告メッセージを表示し、異常終了しないようにした。

# 今後の対応について

以上の通り、CGNS ファイルが壊れていることで異常終了するパターンは1つ発見され、対応された。

しかし、清水先生が遭遇した問題は、ソルバの異常終了などで最後のタイムステップのCGNSファイルが正常に保存できなかったパターンと想定され、そのパターンでの異常終了は再現できていない。清水先生が遭遇した問題については引き続き別途検討が必要。

**Comment by kskinoue0612** [comment]
CGNS ファイルが完全に壊れていて Open できないパターンには対応できていたが、計算結果の出力中に異常終了などし、 HDF5 としては正常で Open もできるが、通常なら存在するはずのフォルダを出力する前に終了したため存在しない、等のパターンへの対応が不十分であり、それが異常終了の原因になり得ることを確認した。通常なら存在するはずのフォルダが存在しない場合のチェックを追加する。

**Comment by kskinoue0612** [comment]
ソルバが、計算結果だけでなく、計算条件や格子を書くこともできる。なので、それらが壊れているプロジェクトを開いて異常終了しないかもチェックする。
