### ISSUE TITLE
Add function to copy screenshot to clipboard

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#144]
Currently, iRIC has function to save screenshot to files (*.jpg, *.png), but it will be convenient if we have
function to copy to clipboard, when user want to paste the image to word or powerpoint, for example.

**Comment by kskinoue0612** [comment]
iRIC do not have "Edit" menu, so let's add interface like below:
- Add "Copy screenshot to Clipboard" action to "File" menu
- Add button for the action above, to main toolbar
- Link Shortcut "Ctrl + C" to the action above, when Subwindow other then Solver Console Window is focused. When Solver Console Window is focused, Ctrl + C should be linked to action to Copy the selected text into clipboard, as currently.

We can emplement this using QClipboard class, I guess.

**Comment by kskinoue0612** [comment]
Hi Scott,

If you have some time for coding while I'm reviewing your pull request, please work on this issue.
I guess this is easy for you, and help Solver developers much when writing documents.
