### ISSUE TITLE
ソルバ実行中に計算格子を編集してしまったあと、プロジェクトを保存しようとしたときの処理について

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1444]
# 課題

ソルバ実行中、プリプロセッサは操作可能なため、アクシデントで、格子を編集してしまうことがある。
その時、ソルバを 1週間など長時間かけて計算していた場合、プロジェクトを保存しようとすると
「格子が編集されているので、プロジェクトを保存すると計算結果が破棄されます」という趣旨のメッセージが出る。
しかし、計算結果の破棄は損失が大きく、避けられる選択肢がほしい。

# 対応方法案

## 案1: プロジェクト保存時の選択肢を増やす

計算実行中に格子が編集された時は以下の選択肢から選べるようにする。
* 計算結果を破棄して格子の変更内容を保存する
* 格子の変更内容を破棄して計算結果を保存する

## 案2: ソルバ実行中はプリプロセッサでの格子関連操作ができないようにする

以下の格子関連の操作を無効化する

* 格子形状の変更
* 格子属性の編集
* 地理情報のマッピング

-> 案1 で対応する

**Comment by starfieldKt** [comment]
https://github.com/i-RIC/prepost-gui/issues/1353
