### ISSUE TITLE
複合型属性のグループ設定の操作によってiRICが異常終了する

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1451]
# 落ちるパターン
デフォルトに指定されているグループを削除したあと、削除後表示されるグループ以外のグループの設定を表示してから`OK`を押すと落ちる

https://github.com/user-attachments/assets/cac322b9-6a4a-48bf-b3f1-f6fe828c7a9b

このため、Defaultを削除した後にItem２～の表示名や値を変更したりするとまずまず落ちる。
Defaultを削除した後に新規グループを追加したりしても落ちる。

# 仕様的にバグにつながっていそうなもの
## その1
どのグループにも「デフォルト値として使う」をチェックを入れずに`OK`を押せてしまう。ただし、自動で先頭のグループがデフォルトになる。

## その2
また、グループを追加した際に自動で連番が振られるが、現在あるグループ数+1で連番がスタートするので同名のグループができやすいため、Defaultを消した後に表示名を修正等の操作につながる。
<video src="https://github.com/user-attachments/assets/29be81a0-963e-49b5-b698-4bb9fcda2967">

# 修正案
* デフォルト設定になっているグループがない場合はOKを押した際に警告を表示する。
* 新規追加されるグループは削除しても連番をリセットしない。

**Comment by kskinoue0612** [comment]
> デフォルト設定になっているグループがない場合はOKを押した際に警告を表示する。

上記については、警告ではなく「デフォルト値として使うグループが指定されなかったため、"xxxx" がデフォルトグループに設定されました。」というメッセージを表示するようにする。自動でデフォルト値として使うグループを設定する機能は現状のまま活かす。

> 新規追加されるグループは削除しても連番をリセットしない。

同じ名前グループが自動でできるのは確かに不便なので、例えば既に Item1, Item2 があった場合、次に作るグループは Item3 になるようにする。 Item2, Item3 しかない場合は空いている Item1 が次の名前になる。
