### ISSUE TITLE
時系列の格子属性の表示がタイムステップ毎に更新されない

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1455]
# 状況
時系列の格子属性（Nays2DFloodのXrainなど)が時間が変化しても表示が更新されない。

時系列ラスタとマッピングされた格子の表示例

https://github.com/user-attachments/assets/d4ea9040-edda-49b7-b5f8-687100cda321

# サンプル
ソルバ
https://github.com/starfieldKt/debug_solver
プロジェクト
[20240913_time_series.zip](https://github.com/user-attachments/files/16989025/20240913_time_series.zip)

**Comment by kskinoue0612** [comment]
すみません、reopen の対応ありがとうございました。 Git の commit に "fix" という単語と #xxxx の文字列をいれると勝手に close されてしまうのを忘れていました。

**Comment by kskinoue0612** [comment]
追加で、以下の修正を行う。

* t = 0 の雨量データが、プリプロセッサに正常に表示されない。
* PC によっては、スライダーが狭く表示されるので修正する。
* 2次元可視化ウィンドウの「入力格子」について、正常に動作するようにする。

**Comment by starfieldKt** [comment]
以下は修正されてRelease版へ反映済み
* t = 0 の雨量データが、プリプロセッサに正常に表示されない。
* PC によっては、スライダーが狭く表示されるので修正する。

**Comment by starfieldKt** [comment]
可視化ウィンドウでの地理情報、入力格子とプリの時系列ラスタの時間が正常に動くように修正された。
時系列ラスタのタイムステップはすべてのウィンドウで共有される。
