### ISSUE TITLE
大規模雨量データを取り扱うプロジェクトの読み込みのボトルネック調査

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1460]
プロジェクトを開いたとき、数分程度の時間がかかる。処理について、どの処理にどの程度時間がかかっているかを調査しする。

ボトルネックがわかったら、そこの高速化について検討する

**Comment by kskinoue0612** [comment]
調査の結果、ラスターデータの読み込みの他、以下の2つの処理が遅いことがわかった。

* ポリゴンデータ読み込み
* 格子にマッピングした雨量データを *.dat ファイルに書き出す処理

これらについても処理の改善による高速化を目指す。

**Comment by starfieldKt** [comment]
#1469 にてボトルネックの一部を修正済み。

* 格子にマッピングした雨量データを *.dat ファイルに書き出す処理

**Comment by starfieldKt** [comment]
雨量データのリストを作成する作業で遅くなっていたのを修正した。

**Comment by starfieldKt** [comment]
https://github.com/i-RIC/prepost-gui/issues/1461
にてポリゴンの読み込みも完了済み

**Comment by starfieldKt** [comment]
https://github.com/i-RIC/prepost-gui/issues/1460#issuecomment-2443468751 の内容を確認した

# 方法
サンプルファイルを開いて格子が表示されるまでの時間を計測。

# スペック
  プロセッサ	Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz   3.60 GHz
  実装 RAM	40.0 GB (39.6 GB 使用可能)
  GPU                Quadro RTX 4000

# サンプルファイル
格子サイズ 401×251 (10万セル)
時系列ラスタ720個を読み込み
https://drive.google.com/drive/folders/1ZoZbk3SA-q1oRFK4uYAuDr7KoUo7hGbt?usp=sharing

# 結果
## 改良前
develop v4.1.0.7092 : 27秒
develop v4.1.0.7094 : 19秒
release   v4.1.0.6947 : 29秒
## 改良後
develop v4.1.0.7095 : 9秒
