### ISSUE TITLE
ポリゴンデータの読み込みの高速化

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#1461]
現状、ポリゴンデータの読み込みは時間がかかる。

調査した結果、 Triangulate ではなく vtkPolygon::New() に時間がかかってしまっている。
これは、 Triangulate を実行するための処理手順を改善することで、大幅に高速化できる可能性がある。具体的には、 vtkPolygon::New() の呼び出し回数が少なくなるよう、オブジェクトを使い回すなどする。

**Comment by starfieldKt** [comment]
改善を確認

# スペック
  プロセッサ	Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz   3.60 GHz
  実装 RAM	40.0 GB (39.6 GB 使用可能)
  GPU                Quadro RTX 4000

82MB程度のファイルを読み込み

# インポート
  develop: 11秒
  release: 20秒

# プロジェクトを開く
  develop: 6秒
  release: 15秒

**Comment by starfieldKt** [comment]
#1460 から派生
