### ISSUE TITLE
描画範囲内に入っていても格子がクリッピングされてしまう

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1474]
格子を拡大していくと描画範囲内に格子があっても当該の格子が何割か画面外にあると表示されない事がある。

格子を細かく確認したいことは結構あるので不便。

https://github.com/user-attachments/assets/8a6de16f-8901-4a0b-9527-8ad098c67c41

**Comment by kskinoue0612** [comment]
少しパンしてもデータが見えるように、マージンを大きめに取るようにする。

**Comment by starfieldKt** [comment]
某モデルの非構造格子でも実用的に問題なくズームインできることを確認しました。

コミット：
80dc54d851dc42c5ba295cab651b95e8a5b1d0b9
