### ISSUE TITLE
「横断測量データから生成」機能で分割点を削除するとiRICが異常終了する

### ISSUE THREAD

**Issue by starfieldKt** [i-RIC/prepost-gui#1485]
リリース版で確認。

すでに追加されている格子生成条件の分割点を削除して、画面の何処かをクリックすると異常終了する。

https://github.com/user-attachments/assets/6166fc22-904b-481a-a0e1-60b6efb06e61

サンプルプロジェクト
[grid_Create.zip](https://github.com/user-attachments/files/17912052/grid_Create.zip)

**Comment by starfieldKt** [comment]
行、または列すべてを選択して削除した場合は発生しない。
そのため分割点の総数が合わない事によって落ちている可能性あり

**Comment by kskinoue0612** [comment]
削除前に、マウスカーソルを点の真上に持っていって、ドラッグ中ステータスになってから削除すると落ちる。

**Comment by starfieldKt** [comment]
落ちないことを確認した。
