### ISSUE TITLE
GridCreatingConditionTriangle::addRefinementPolygon causes failed assertion in GridCreatingConditionTriangle::deselectAll

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#152]
Steps to reproduce:
1. Download [tests.zip](https://github.com/i-RIC/prepost-gui/files/1227437/tests.zip).
2. In Debug mode open test_ok1.ipro.
3. Select 'Grid Creating Condition' within Object Browser.
4. Click 'Add Refinement Region'

**Comment by kskinoue0612** [comment]
Fixed by

https://github.com/i-RIC/prepost-gui/pull/153
