### ISSUE TITLE
iRIC 3.0 Contour Legend Setting help message example is invalid

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#17]
1. 2016/10/28 on Keisuke's machine
2. OS Windows 7 Enterprise SP1
3. Version of iRIC
   iRIC (x64) 3.0.0.6178
4. What? How?
   On Color Legend Setting dialog in Post2D window etc, Label Display Format help message is as follows:

`Specify the number format in printf format. For example:`
`"-%.3f" for 3.141592 --> 3.141`
`"-%.3e" for 12300 --> 1.23E+004`

But it is wrong. the help message should be as follows:

`Specify the number format in printf format. For example:`
`"%5.2f" for 3.141592 --> 3.14`
`"%4.2e" for 12300 --> 1.23E+004`

**Comment by kazutake** [comment]
Format specification place is not active and it seems not working. Please check it again.
