### ISSUE TITLE
iRIC 2.3 Deleting polygon crashes iRIC GUI when there is no point defined.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#18]
1. 2016/10/28 on Keisuke's machine

2. OS Windows 7 Enterprise SP1

3. Version of iRIC
iRIC (x64) 2.3.10.6381

4. What? How?
When user tries to delete a polygon before any points are defined, iRIC GUI crashes.

**Comment by kazutake** [comment]
OK. I confirmed above.
