### ISSUE TITLE
iRIC 3.0 Importing Shape file that contains no polygon will crash the GUI.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#20]
1. 2016/10/28 on Keisuke's machine

2. OS Windows 7 Enterprise SP1

3. Version of iRIC
iRIC GUI 3.0 alpha2

4. What? How?
When use imports ESRI shape file, that contains no polygon, iRIC GUI crashes.

Try to reproduce the bug using 01_yugou_h=10.0.shp, that is included in shp_edit.zip, that is attatched to a comment in #7.

**Comment by kazutake** [comment]
OK. I confirmed above.
