### ISSUE TITLE
Change 2D Vis window item name

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#206]
Scalar -> Scalar (node)

**Comment by scharlton2** [comment]
Hi Keisuke,

I think we should be consistent with capitalization:

Currently:
iRICZone
   Scalar
   ...
   Particles (auto)
   ...
   Scalar (Cell Center)

New 1:
iRICZone
   Scalar (node)
   ...
   Particles (auto)
   ...
   Scalar (cell center)

New 2:
iRICZone
   Scalar (Node)
   ...
   Particles (Auto)
   ...
   Scalar (Cell Center)

Let me know which one you prefer.

Thanks
Scott
