### ISSUE TITLE
Bird's-Eye doesn't render Contours using 'Color Fringe' or 'Isolines'

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#211]
Bird's-Eye doesn't render Contours using 'Color Fringe' or 'Isolines' options when using an unstructured grid:
[WorkingSolution.zip](https://github.com/i-RIC/prepost-gui/files/1512616/WorkingSolution.zip)

There seems to be no problems for structured grids:
[Braid_2_3.zip](https://github.com/i-RIC/prepost-gui/files/1512626/Braid_2_3.zip)

This problem exists for at least the following commits:
fcfbf6417c58883cf6da583dd6cb06f5046f744a 
2e84789ea7bb5fe76be5eadcea32d514cd73bd86 (master)

**Comment by scharlton2** [comment]
Hi Keisuke,

If you know a commit that worked with unstructured grids, let me know and I'll bisect to the commit that broke it.

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

This was caused by the "Elevation" being called "Bed Elevation" in the SToRM solver.  See https://github.com/i-RIC/prepost-gui/pull/266#issuecomment-362456014 and https://github.com/i-RIC/prepost-gui/pull/266#issuecomment-363291550.

So I'll close this issue manually.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Thanks, Scott!
