### ISSUE TITLE
Post windows (vis window, chart window etc) settings are saved to individual XML files.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#222]

**Comment by kskinoue0612** [comment]
It sometimes happen that XML for post windows are broken, and because of that we have to abandon whole project.

To avoid this, we read individual XMLs, and if some of them is broken, we read only the others. In that way we do not have to abandon whole project, but only the post-processor window.

**Comment by scharlton2** [comment]
Closed by pull request #989
