### ISSUE TITLE
iRIC 2.3 Contour Legend setting Format textbox is disabled

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#23]
1. 2016/10/31 on Keisuke's machine
2. OS Windows 7 Enterprise SP1
3. Version of iRIC
   iRIC (x64) 2.3.11.6405
4. What? How?
   On Color Legend Setting dialog in Post2D window etc, Label Display Format text box is disabled.

**Comment by kazutake** [comment]
OK. I confirmed above.
