### ISSUE TITLE
iRIC 2.3 Polygon importing fails when the polygon has multiple same points in a ring.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#25]
1. 2016/10/28 on Keisuke's machine
2. OS Windows 7 Enterprise SP1
3. Version of iRIC
   iRIC (x64) 2.3.11.6405
4. What? How?
  When user tries to import polygon data, that has multiple same points in a ring, iRIC GUI crashes.

![screenshot](https://cloud.githubusercontent.com/assets/4031569/19912592/d83de54c-a0de-11e6-94a5-53eb52e35ee9.png)

**Comment by kazutake** [comment]
The word "Error" is in the Message. But I think it should be "Warning". For example,

Warning: Specified shp file has the polygon in which there are the same point coordinates. So iRIC deleted those polygons and imported other polygons. Deleted polygons is followings.

1111
222
21

**Comment by kazutake** [comment]
iRIC skip reading polygon which has the same point.
