### ISSUE TITLE
iRIC 3.0 Polygon importing fails when the polygon has multiple same points in a ring.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#26]
1. 2016/10/28 on Keisuke's machine
2. OS Windows 7 Enterprise SP1
3. Version of iRIC
   iRIC (x64) 3.0 alpha2
4. What? How?
  When user tries to import polygon data, that has multiple same points in a ring, iRIC GUI crashes.

![screenshot](https://cloud.githubusercontent.com/assets/4031569/19912592/d83de54c-a0de-11e6-94a5-53eb52e35ee9.png)

**Comment by kazutake** [comment]
Please tell the status.

**Comment by kskinoue0612** [comment]
Tested with the attached shape file.
Now iRIC do not crash, but says that the data is invalid, and the data is ignored.

[shape.zip](https://github.com/i-RIC/prepost-gui/files/1221080/shape.zip)
