### ISSUE TITLE
Make it possible to re-map grid attributes only partial polygons.

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#27]
In current version, we can select attributes we want to map into grid. But it is all polygons or nothing. Sometime we would like to map a part of polygons, only because several part of grid attribute is modified manually. Those of modification would be gone all or nothing mapping.

**Comment by kskinoue0612** [comment]
Maybe this can be fixed like this:

We make function so that user can select mapping algorithm about polygon onto cell attribute, from:
- Map only when all the points that consist cell are included in the polygon
- **Map when the center of the cell is included in the polygon**

**Comment by kskinoue0612** [comment]
This is a duplicate issue of #258, and closed already.
