### ISSUE TITLE
Strange warning when canceling *.riv import

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#276]
To reproduce:

1. Start new project in iRIC
2. Import->Geographic Data->Elevation... choose a "River Survey data (*.riv)" file.
3. Press "Cancel" on River Survey Data Import Setting dialog.

![image](https://user-images.githubusercontent.com/7538707/36452037-31b44138-1650-11e8-9750-b6d3f8feeeed.png)

![image](https://user-images.githubusercontent.com/7538707/36452050-3c530516-1650-11e8-8397-bd53507dbd87.png)

To fix, will need to throw an exception from `bool importData(GeoData* data, int index, QWidget* w)`  or
change return type to an enum to handle more than two values.

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for reporting.
Now I am out of office. When I’m back, I’ll think about how to fix this.

Thanks,
Keisuke
