### ISSUE TITLE
Data import error checking improvement

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#282]
Currently. River survey data import error checking is not very good.

For example string value is entered when int or real value is expected, no error message is
output, but ignored or read as value zero, and user does not notice.

It is a big issue when user wants to use very big river survey data.

Importing other data, like *.tpo, *.shp, grids, measured data etc. are more simple, but we should improve them too.

**Comment by kskinoue0612** [comment]
Output log about importing geographic data.

**Comment by kazutake** [comment]
できているはず？
