### ISSUE TITLE
iRIC 3.0 HDF5 DLL issue

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#29]
iRIC 3.0 and related libraries should be built with 
build option HDF5_DISABLE_VERSION_CHECK = 1

Built in this way, iRIC does not crashes even when HDF DLL version is not the same
to that used when compiling iRIC.

**Comment by kskinoue0612** [comment]
It became apparent that disabling version check can not be done in compiling option. It can be disabled only through environmental variable "HDF5_DISABLE_VERSION_CHECK".

I think we add description about how to handle the error, in the iRIC GUI manual.

**Comment by kazutake** [comment]
Please tell the status.

**Comment by kskinoue0612** [comment]
Document is prepared.

https://iric-gui-user-manual-jp.readthedocs.io/ja/latest/07/hdf_warning.html
https://iric-gui-user-manual.readthedocs.io/en/latest/07/hdf_warning.html
