### ISSUE TITLE
iRIC 3.0  River crosssection rotation bug

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#30]
1. 2016/11/23 on Kazutake's machine
2. OS Windows 10
3. Version of iRIC
   iRIC (x64) 2.3
4. What? How?
  When rotating river cross-section on dialog, Selecting 'Angle from river centerline', and inputting the angle, the result is different from something we expect.

![image](https://cloud.githubusercontent.com/assets/7007415/20551441/b29111ec-b183-11e6-9c57-367ce5f0225a.png)

![image](https://cloud.githubusercontent.com/assets/7007415/20551448/c2d22cd0-b183-11e6-873a-4cb98f812e0a.png)

**Comment by kskinoue0612** [comment]
Fixed in iRIC 3.0 beta2.

**Comment by kazutake** [comment]
OK! I've confirmed.

**Comment by kazutake** [comment]
OK! I've confirmed.
