### ISSUE TITLE
River Survey Data center line position import

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#31]
Extend river survey data file format so that User can import/export the position of River center line.

We extend the file format like below:

> (Line name), (point count), (left limit), (left div point), (right div point), (right limit), **(river center position)**
>(Line points...)

- River center position value is the distance between left limit data and center line
- We check that center line position is between (left div point) and (right div point). If not, message is shown and importing fails.

**Comment by kskinoue0612** [comment]
This function is important for simulation to for re-creating simulation.

**Comment by kskinoue0612** [comment]
This issue is closed, because #154, #205, #224 are implemented.

**Comment by kskinoue0612** [comment]
Sorry, mistake.

**Comment by kskinoue0612** [comment]
I close this, because we've implemented it with #885.
