### ISSUE TITLE
Update images from the Culvert Analysis Program 

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#320]
Hi Keisuke,

I didn't know if you have CAP under source control so I put it here.  Here's a few changes to the CAP solver images (feets -> feet);

alignment_mitered_english.png:

![alignment_mitered_english](https://user-images.githubusercontent.com/7538707/39947987-30386742-5531-11e8-95f6-c85c1de13182.png)

alignment_skewed_english.png:
![alignment_skewed_english](https://user-images.githubusercontent.com/7538707/39948421-23c58c86-5533-11e8-8fef-66ce64248dde.png)

alignment_unskewed_english.png:
![alignment_unskewed_english](https://user-images.githubusercontent.com/7538707/39948430-30ab230c-5533-11e8-9dd8-15fdc2f43b07.png)

approach_english.png:
![approach_english](https://user-images.githubusercontent.com/7538707/39948436-36707cba-5533-11e8-9a4e-8df4b56314ae.png)

flows_tailwater_english.png:
![flows_tailwater_english](https://user-images.githubusercontent.com/7538707/39948440-3b8c7a5a-5533-11e8-9a9d-26a7b247b3f4.png)

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scot,

Thanks for the information.
I'll update the images when I'm back to office next week.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Updated images are now bundled with CAP in iRIC 3.0 installer.
