### ISSUE TITLE
v3.0 Reading error : Xrain

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#33]
iRIC is crashed during reading Xrain data. Please fix it.
Sample Data set cannot attach here.

**Comment by kazutake** [comment]
Also above function should extend for LINUX version.

**Comment by kskinoue0612** [comment]
When Xrain data is saved in path with Japanese characters, importing data fails.
I'm sorry, but this is the limitation of the tool that NIED provided.

**Comment by kskinoue0612** [comment]
Now fixed in master branch. When the path includes Japanese characters, the data is temporarily copied to temp folder created in workspace.

**Comment by kazutake** [comment]
I don't understand what is the correct work.
