### ISSUE TITLE
Make SRTM data max zoom level smaller

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#339]
Currently, the max zoom level value of USGS SRTM is set to be 15. This corresponds to resolution 4m around Japan. 

But actually SRTM data resolution is 90m. So the zoom level is too big. When user download SRTM data with zoom level 15. we get thousands of points with the same value.

We should make the max zoom level value to be 11, because it corresponds to about 60m around Japan.

**Comment by scharlton2** [comment]
Hi Keisuke,

I think that's no longer true.  I think that the data was declassified in 2014, and that it is available world-wide at approximately 30m resolution (at latitudes between 50 degrees North and South) .

see https://lta.cr.usgs.gov/SRTM1Arc

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your information. So the max zoom level should be 13, right?
Anyway, I'll check again about the appropriate max level when I engage this issue.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I think so.  Based on https://wiki.openstreetmap.org/wiki/Zoom_levels it looks like 12 is 38.187 m/pixel and 13 is 19.093 m/pixel.

Thanks,
Scott
