### ISSUE TITLE
Parallel execution of heavy operations related to VTK

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#341]
It seems that VTK heavy operations are not done in multi-threaded execution in iRIC.

For example if we do particle tracking on post2d visualization window on PCs with 8 cores, CPU usage is only 15%. From that, we can assume that it is currently executed on single core.

VTK documentation says that VTK support multi-threaded execution, so read the document deeply, and use multi-threaded execution for heavy operations with VTK.

https://www.vtk.org/parallel-processing/

**Comment by kskinoue0612** [comment]
It seems that when we upgrade VTK to 8.0 or higher, this is automatically achieved.

https://blog.kitware.com/vtk-8-0-0/

The VTK 8.0 release note says that in VTK 8.0 VTK-m is introduced, which provides filters that run on GPUs and many-core processors.

**Comment by kazutake** [comment]
ニーズはあると思われるが、今後改めて要望が出てきたときの考える
