### ISSUE TITLE
Add function to specify unit when manually inputting the information about time, when importing NetCDF

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#347]
Currently, when automatic time format recognizing fails, the dialog below is shown, and user are asked to input the date that corresponds to value 0.
But on the dialog user can input only the date, not unit, like seconds, minutes.

Add combo box to edit units, to select from the followings:
* years
* days
* hours
* minutes
* seconds

I omitted months, because it is not straight forward, because number of days differs.

![date_dialog](https://user-images.githubusercontent.com/4031569/40901739-78723770-680c-11e8-9e7b-525f787629ca.png)

**Comment by scharlton2** [comment]
Hi Keisuke,

I started working on this a while ago but got stuck when I didn't know how units were handled in i-RIC.  Currently it looks like the time units imported from an netcdf file are always saved in seconds.  But, if we were to change the units to anything else how would the model be notified?  The time is stored in the cgns file right?  It looks like there are only three ways to [store time units](https://cgns.github.io/CGNS_docs_current/midlevel/physical.html#dimensionalunits) as null, seconds or user_defined.

Let me know if I'm missing something simple.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for working on this.

As you've noticed, iRIC currently handles time values in seconds always. Time values imported from NetCDF is saved as unit time (seconds from 1970/1/1 00:00:00) in CGNS files. It is an limitation that we can not handle data older than 1970, but for iRIC applications this is acceptable, I think.

So, the implementation that I've planed is as follows:
* Add a combobox to `GeoDataNetcdfImporterDateSelectDialog`, to select units from "years", "days", "hours", "minutes", "seconds". The selected value is returned with `QString GeoDataNetcdfImporterDateSelectDialog::units()`, that we are going to add.
* In `GeoDataNetcdfImporter::convertTimeValues()`, get the units that user selected on the dialog, with line like below:

```
unit = dialog.unit()
```
It should be added just after https://github.com/i-RIC/prepost-gui/blob/master/libs/geodata/netcdf/geodatanetcdfimporter.cpp#L468

Anyway, this is a temporary support, and when we finish #346, we'll not need to select original date and units for most types of NetCDF files.

Thanks,

Keisuke Inoue
