### ISSUE TITLE
Make verification dialog non-modal

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#358]
Currently, Verification dialog (to compare calculation result and measured data) is modal dialog, and can not do other operations when it is open.

I think we can make dialog non-modal, like other visualization windows.

**Comment by scharlton2** [comment]
Hi Keisuke,

I thought I was ready to make a pull request for this issue until I tried to remove the calculation results and it caused iRIC to crash.  So I looked at how "Graph Window" and  "Scattered Chart Window" behaved (without looking at the code yet).  

It seems that when deleting calculation results that the data is stored while the project is still loaded, but if you try to reopen the project the chart is no longer drawn.  And, even if you re-run the project the "Graph Window" and "Scattered Chart Window" no longer do anything.

Is this the way it works?  I'm going to look at the code to see how it handles this, but I wanted to make sure I asked you before you are done for the weekend.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your contact, and the work on this issue.

> It seems that when deleting calculation results that the data is stored while the project is still loaded, but if you try to reopen the project the chart is no longer drawn.  And, even if you re-run the project the "Graph Window" and "Scattered Chart Window" no longer do anything.
>
> Is this the way it works?  I'm going to look at the code to see how it handles this, but I wanted to make sure I asked you before you are done for the weekend.

Based on your comment, I've tested with the newest Developer version (3.0.18.6323). You are right. Currently, it works in that way. I know it is not a good behavior. Thank you for reporting.

To think about how I can fix the issue, I've looked into the code of the following methods, that are called while loading data from project file.

* Graph2dHybridWindowResultSetting::init()
* Graph2dScatteredWindowResultSetting::init()

it seems that to make them work, it is needed that calculation result is loaded from CGNS file correctly before they are called, because it needs calculation result name list etc. It seems that it is not an easy fix.

In my understanding, It has not be reported, because many people do not use chart windows in that way. Many people run solver, open chart windows, and save the project, without deleting calculation result.

I think we should register the issue you've found to github and fix it later. But to close this issue, it will be enough that we can use verification windows with "Normal workflow" like below:

### Procedure 1: Normal workflow

1. Open verification window.
2. User delete the calculation result -> Verification window is cleared.
3. User run the solver again -> Verification window is updated and show chart with new result.
4. Save project with verification window open (without deleting calculation result)
5. Open project with verification window -> verification window is restored correctly

If it is easy, it is better to achieve the following, but it is optional, because other
chart windows do not support this either, currently.

### Procedure 2: Save verification window with calculation result deleted

1. Open verification window.
2. User delete calculation result -> Verification window is cleared.
3. User save the project with verification window open.
4. User open the project -> Verification window is restored correctly
5. User run solver again -> Verification window is updated and show chart with new result.

Scott, I do not know the detailed implementation of verification window currently. Do you think that you can achieve "Procedure 1" ? Currently that will be enough.

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I just now saw your email.  I pushed my latest version, it sort of works except for when the solver is re-run.

Here's the file (results removed) I've been using to test with:
[issue-358.zip](https://github.com/i-RIC/prepost-gui/files/4606815/issue-358.zip)

Thanks for your help,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for pushing the commits.
OK, I'll look into the code, and use the file you've uploaded to test it.
When I've got progress, I'll share with you and ask you to check.

Thanks,
Keisuke
