### ISSUE TITLE
When using Longitude-latitude coordinate system cannot import google background images

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#369]
1. Set coordinate system to WGS 84 (EPSG:4326).
2. Import->Google Map Background Image... -- most often I'll get this warning: "This function can not be used when there is no data to be drawn." But, sometimes it'll just spin in the
`int TmsUtil::calcNativeZoomLevel(const QPointF& lonlat, double targetMeterPerPixel)`
routine because the `targetMeterPerPixel` argument is negative.

**Comment by kskinoue0612** [comment]
I close this because function to import google background images is removed in #416.
