### ISSUE TITLE
Cell center contour is drawn behind Background Image (Internet) on Post2D window

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#376]
Cell center contour is drawn behind Background Image (Internet) on Post2D window.

Please open the project in Braid-Cell-8.zip that is attached to the following comment, and check on one of the background Image (Internet) item, like "Google Map (Road)".

https://github.com/i-RIC/prepost-gui/issues/154#issuecomment-342372297

**Comment by scharlton2** [comment]
Hi Keisuke,

Just to let you know, that you can copy previous uploads be pressing the three dots, selecting edit, and copying the link. ([Braid-Cell-8.zip](https://github.com/i-RIC/prepost-gui/files/1448670/Braid-Cell-8.zip)).

Thanks,
Scott
