### ISSUE TITLE
iRIC 2.3 Polygon import fails when x coordinates of polygon points are exactly the same

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#38]
1. 2016/12/22 on Keizuke's machine
2. OS Windows 7
3. Version of iRIC
   iRIC (x64) 2.3.11.6420
4. What? How?
  When the X coordinates of polygon points are exactly the same, iRIC recognizes it to be a invalid shape, and fails to import polygon.

**Comment by kskinoue0612** [comment]
The error_polygon.shp can be used to test it. Error occurs when imported into 2.3.11, but when imported into 2.3.12, no error occurs.
[error_polygon.zip](https://github.com/i-RIC/prepost-gui/files/668299/error_polygon.zip)

**Comment by kazutake** [comment]
OK
