### ISSUE TITLE
Import GeoTIFF error.  Proj. with GeoTIFF crashes upon re-open of saved file

### ISSUE THREAD

**Issue by rmcdgstl** [i-RIC/prepost-gui#46]
iRIC v3 opens this geotif file (in attached zip file) but doesn't show elevations correctly.  Also when project with this file is saved, it crashes when reopened.  The file in .zip file opens correctly in other software such as Global Mapper or ARC.  Thanks Keisuke

[E.zip](https://github.com/i-RIC/prepost-gui/files/851521/E.zip)

**Comment by kskinoue0612** [comment]
This problem is now fixed. GeoTIFF I/O had bug.

**Comment by kazutake** [comment]
>Rich

Did you confirm this problem fixed?

**Comment by kskinoue0612** [comment]
Rich and Keisuke checked, and it worked.
