### ISSUE TITLE
Scalar Bar color problem

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#48]
Scalar bar color behavior changed from 2.3 to 3.0.
![screenshot](https://cloud.githubusercontent.com/assets/4031569/24895922/a2c9a83e-1ecd-11e7-8ecb-9c06b33375cc.png)

**Comment by kazutake** [comment]
?????

**Comment by kskinoue0612** [comment]
Hi all,

I've looked into the code, and noticed that this is because of change of VTK implementation.
In vtkScalarBarActor.cxx, The colors of scalar bar is calculated in the code below:

```
    double rgbval;
    if (this->LookupTable->UsingLogScale())
      {
      rgbval = log10(range[0]) +
        i * (log10(range[1]) - log10(range[0])) / this->P->NumColors;
      rgbval = pow(10.0, rgbval);
      }
    else
      {
      rgbval = range[0] + (range[1] - range[0]) *
        (i / static_cast<double>(this->P->NumColors));
      }
    lut->GetColor(rgbval, rgba);
```

The problem is in the code below:

```
      rgbval = range[0] + (range[1] - range[0]) *
        (i / static_cast<double>(this->P->NumColors));
```

In the old VTK, it used to be like below, I guess:

```
      rgbval = range[0] + (range[1] - range[0]) *
        (i / static_cast<double>(this->P->NumColors - 1));
```

For example, when NumColors = 5, range[0] = 0, range[1] = 4,
old VTK showed colors for values 0, 1, 2, 3, 4,
but now VTK shows colors for values 0, 0.8, 1.6, 2.4, 3.6, i. e. the minimum value for each range.

To make iRIC v3 behave the in the same way to iRIC v2, I'll create vtkCustomScalarBarActor, that
is the slightly modified version of vtkScalarBarActor, and use it in iRIC.
