### ISSUE TITLE
Add function to import GeoTIFF image as background image

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#482]
For background images, currently JPEG / PNG / TIFF with world files (*.jgw, *.pgw, *.tfw) are supported, and imported into appropriate position. But GeoTIFF is not supported, and it is imported into the default position.

Add function to load origin position and x-scale, y-scale from GeoTIFF.

**Comment by kskinoue0612** [comment]
Maybe it is better to close this issue, by reading background image using GDAL, instead of custom implementation of reading *.jgw, *pgw, *.tfw. I guess GDAL will automatically read *.jgw, *.pgw, *.tfw, if they exists.

**Comment by kazutake** [comment]
It is good for users if it will come into the iRIC software. But more voice of user would be required.
