### ISSUE TITLE
iRIC v2.3 Polygon opacity function corrupted

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#5]
**1. Date found**
- 2016/9/27
- Reported by Hamaki-san through mail

**2. Environment**
・OS:Windows7 64-bit

**3. iRIC Version**
iRIC(x64) 2.3.10

**4. The problem**
It is not possible to make the polygon transparent. Even if we change "Transparancy" value more than 0%, nothing occurs.

**Comment by kazutake** [comment]
Clear
