### ISSUE TITLE
ver2.3　Manning roughness and png

### ISSUE THREAD

**Issue by tomokyuuu** [i-RIC/prepost-gui#50]
計算結果の存在するファイルを開くと，マニング粗度係数のポリゴンのチェックが付いていても，付いていなくても，勝手に表示される．背景画像としてPNGファイルをインストールすると，格子の上に背景画像が描画される（JPGは格子の下に背景画像が描画される）．

**Comment by kazutake** [comment]
Please tell the status.

**Comment by kazutake** [comment]
Please check this for v3.
