### ISSUE TITLE
Grid control point for "Create grid from river survey data" selection with shift button causes iRIC crash

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#508]
When user try to select grid control points with shift button, the points should be selected with XOR mode, but that operation causes iRIC crash.

**Comment by scharlton2** [comment]
Sorry, Keisuke,

But I'm unable to reproduce this.  Is this what you mean by a "Grid control point"?

![image](https://user-images.githubusercontent.com/7538707/56015401-2ec55b80-5cb6-11e9-806d-ea0e6158bbf5.png)

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your quick response.
The grid control points are the yellow points in the screenshot below.

![issue-508_screenshot](https://user-images.githubusercontent.com/4031569/56017681-fe73d080-5d3a-11e9-8180-74563379e591.png)

The issue is related to issue #507, and you can reproduce the issue after merging #509.

Please use the following file to reproduce the issue, after merging #509.
[issue-508.zip](https://github.com/i-RIC/prepost-gui/files/3071963/issue-508.zip)
