### ISSUE TITLE
cgns 64-bit bug

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#52]
[srh2d_iRICv3.zip](https://github.com/i-RIC/prepost-gui/files/963431/srh2d_iRICv3.zip)
[hmc_3-30-17_3.zip](https://github.com/i-RIC/prepost-gui/files/963435/hmc_3-30-17_3.zip)

**Comment by scharlton2** [comment]
Here's a project along with a solver that I've
been working with.  When I open it it tries to read the grid dimensions it receives
a huge integer and when it attempts to allocate a vector to hold the coordinates
it runs out of memory and throws a bad_alloc exception.  For some reason it
only occurred in the release build.

**Comment by kskinoue0612** [comment]
That was because CGNS library was built with ENABLE_64 option. iRIC develop environment setup manual had bug.
Thanks to Scott, iRIC development environment can be automatically setup, so this issue will not happen any more.
