### ISSUE TITLE
Project can not be saved after stopping calculation

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#54]
1. 2017/5/11 on Mr. GAMOU's machine
2. OS Unknown
3. Version of iRIC
   iRIC (x64) 3.0.0 6189
4. What? How?
  When user stops running solver (by pressing "Stop" button", sometimes saving project file fails. When it failed the following save operations always fails.

**Comment by kskinoue0612** [comment]
It seems to be caused by CGNS related problem. I imagine, in some condition, solver keeps the handle to CGNS file(?), and because of that, iRIC GUI can not open the CGNS file.

**Comment by kazutake** [comment]
Please tell the status.
