### ISSUE TITLE
Arrow size setting for unstructured grid calculation result on 2D visualization window is not working.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#55]
When opening the dialog the arrow setting default always becomes like the following:
- arrow size = 3
- arrow width = 1

**Comment by kskinoue0612** [comment]
Now fixed on master branch.

**Comment by kskinoue0612** [comment]
Sample data for testing is added here.

[result.zip](https://github.com/i-RIC/prepost-gui/files/1087685/result.zip)

**Comment by kazutake** [comment]
OK
