### ISSUE TITLE
Boundary condition setting tries to map even when boundary condition setting does not exist.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#56]
When user add boundary condition, not boundary condition setting, iRIC GUI ask user to map boundary condition setting to grid. 
This is not correct, because there is not boundary condition setting data if created in this case.

**Comment by kazutake** [comment]
Please tell the status.

**Comment by kskinoue0612** [comment]
Please use the attached file here, to test the pull request.
Before merging the pull request, when the attached project is opened, and you try to start the solver,
The message "Boundary Condition Setting "New Inflow" is not mapped ....." is shown.

After merging the pull request, the warning message is not shown.

[test.zip](https://github.com/i-RIC/prepost-gui/files/1221283/test.zip)
