### ISSUE TITLE
Add function to set the ratio between vertical distance and horizontal distance on cross section window

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#564]
On cross section window, now user can control the ratio in vertical direction and horizontal direction individually. But for actual work, user often want to visualize the data with ratio like 1:5, 1:10, 1:20, 1:100 etc.

To satisfy such need, add widgets like below:

![interface](https://user-images.githubusercontent.com/4031569/65940939-c38a6400-e464-11e9-8668-63f87decbaa4.png)

* User can control the aspect ratio by inputting value to spin box.
* User can fix the aspect ratio by checking on "Fix aspect ratio" checkbox. When aspect ratio is fixed, user can still change the region to show by panning, and zooming in/out.
* User can fix the region to show by checking on "Fix region" checkbox. When region is fixed, operation for changing aspect ratio, zooming in/out, and panning are all disabled.

**Comment by scharlton2** [comment]
Hi Keisuke,

Everything seems to work except that I can still zoom in and out using the mouse scroll wheel when the 'Fix region' checkbox is checked (panning is correctly disabled).

Thanks,
Scott
