### ISSUE TITLE
River survey data not mapped correctly to grid node when cross sections are crossed

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#57]
1. 2017/6/1 on Keisuke's machine
2. OS Windows 7
3. Version of iRIC
   iRIC (x64) 3.0.0 6189
4. What? How?
River survey data are not mapped correctly to grid node when cross sections are crossed.

[test.zip](https://github.com/i-RIC/prepost-gui/files/1043399/test.zip)
![screenshot](https://cloud.githubusercontent.com/assets/4031569/26661435/a71b8264-46b8-11e7-86c1-a3e15ea78775.png)

**Comment by kskinoue0612** [comment]
Fixed in master branch now.

**Comment by kazutake** [comment]
OK. But, It is hard for us to grab the points which make a calculation region.

**Comment by kskinoue0612** [comment]
I've registered the "grabbing" problem as a separate issue below.
https://github.com/i-RIC/prepost-gui/issues/86
