### ISSUE TITLE
Drawing graph for base iterative data while running solver causes CGNS I/O error.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#58]
1. 2017/6/1 on Keisuke's machine
2. Windows 7
3. Version of iRIC
   iRIC (x64) 3.0.0 6190
4. What? How?
   Drawing graph for base iterative data while running solver causes error. Do the following.

    1. Open test.ipro.
    2. Start running solver.
    3. While solver is running, open Graph window and draw graph with Time - Discharge.
        (This sometime causes error message 「グラフウィンドウの初期化に失敗しました。計算結果が正しく読みこまれていません。」)
    4. Press reload button, for many times. It sometimes causes 「計算結果の読み込み中にエラーが発生しました。」

When CGNS file I/O goes wrong, it never succeed to open again, and project can not be saved. It is a BIG problem.
[test.zip](https://github.com/i-RIC/prepost-gui/files/1043757/test.zip)

Generally speaking, CGNS file I/O is not stable currently, and when graph window is used, the error occurs more frequently, it seems.

**Comment by kazutake** [comment]
What's going on?
