### ISSUE TITLE
Arrow drawing bug on 3D visualization window

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#59]
1. 2017/6/1 on Keisuke's machine
2. Windows 7
3. Version of iRIC
   iRIC (x64) 3.0.0 6190
4. What? How?
   When operated in the following order, arrows are not shown.
   1. Setup arrows with at least one surface.
   2. Check off the Surface under Arrows
   3. Change Time slider
   4. Check on the Surface under Arrows.

[2dv_bs_test2.zip](https://github.com/i-RIC/prepost-gui/files/1043768/2dv_bs_test2.zip)

**Comment by kskinoue0612** [comment]
Fixed in master branch.

**Comment by kazutake** [comment]
What's happen?

**Comment by kazutake** [comment]
OK
