### ISSUE TITLE
iRIC 2.3 Polygon loading corrupted

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#6]
**1. Date found**
- 2016/9/27
- Reported by Hamaki-san through mail

**2. Environment**
・OS:Windows7 64-bit

**3. iRIC Version**
iRIC(x64) 2.3.10

**4. The problem**
When the polygon is loaded from project files (*.ipro or project.xml), the polygon is now filled (frames only are shown), and mapping polygon to grid attributes fails.

**Comment by kazutake** [comment]
Above problem was cleared on v2.3.11.6382 .
