### ISSUE TITLE
When iRIC Maintance window is launched warning message is shown about how to update iRIC GUI.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#62]
When iRIC Maintainance window is launched from iRIC GUI menu

> Option -> Maintanance

warning message "When you update iRIC, you need to close iRIC before launching iRIC Maintainance.
When you have iRIC windows other than this, close them manually." should be shown first.

**Comment by kskinoue0612** [comment]
Implemented on master branch.

**Comment by kazutake** [comment]
OK！
