### ISSUE TITLE
Periodical checking for update implementation

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#63]
- In Preference Dialog, the followings are added:
    - "Check for update periodically" checkbox
    - "Interval between checking (days) spinbox (box to edit integer): min = 1, max = 365, default = 28

- When iRIC is launched, a dialog will be shown when the condition below is satisfied:
    - "Check for update periodically" is enabled
    - "Interval" days have passed after the last checking

- The dialog message is "XX days have passed after launching iRIC Maintainance for the last time. Do you want to launch iRIC Maintainance?". The buttons are "Launch iRIC Maintainance" and "Cancel".

**Comment by kskinoue0612** [comment]
Implemented on master branch.

**Comment by kazutake** [comment]
OK
