### ISSUE TITLE
Font sizes on color bar

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#642]
Reported by Jonathan 12/5/2019:

> We noticed while teaching our class that the font size selector in the editing dialog for the colorbar does not work. I think it used to work.

I have reproduced:

![image](https://user-images.githubusercontent.com/7538707/70252243-51711c80-173e-11ea-9ea3-c2f183461bfc.png)

I'm not sure if this used to work or not.  I think the 'Font Setting' dialog was recently changed to be standardized for post2d windows (see #587).  

It might not be possible to set the font size directly since the font size is automatically scaled when clicking on the scalarbar and dragging the mouse:

![image](https://user-images.githubusercontent.com/7538707/70253013-9cd7fa80-173f-11ea-99c7-880685b23078.png)

Scott

**Comment by kskinoue0612** [comment]
I close this, because #762 is closed.
