### ISSUE TITLE
Attribute Browser displays wrong J index when viewing (cell center) scalar

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#678]
Using iRIC (develop) 3.0.18.6307

Steps to reproduce:
1. Start iRIC
2. Close iRIC Start Page
3. Import->Calculation Result... ([case_solstd.cgn](https://github.com/i-RIC/prepost-gui/files/4195010/case_solstd.zip))
4. Open new 2D Post-Processing Window
5. Turn off all Particles
6. Turn on all grid lines
7. Right-click Scalar (cell center) -> CCDepth
8. Select "Show Attribute Browser"
9. Hover mouse over left-most cell
10. J index is zero instead of 1

![image](https://user-images.githubusercontent.com/7538707/74378329-fcd3c880-4da2-11ea-87bd-137cbf89ef0d.png)

**Comment by kskinoue0612** [comment]
Hi Scott,

I've made sure that commit (735cae2) fixed this bug.

Thanks,
Keisuke
