### ISSUE TITLE
When grid is created with grid generator, geographic data is not mapped to grid attributes

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#694]
When user create grids with grid generators, geographic data is not mapped to grid attributes, and users have to map manually.

It seems that this issue occurs only with external grid generators developed as separate programs in FORTRAN or C.

**Comment by kskinoue0612** [comment]
Hi Scott,

Today, I've investigated detail of this issue. Now I've understood why this happened, and I want to have a discussion about how to close this issue.

## The reason of the issue

As you know, when we create grid with "Multifunction Grid Generator", even if user click on "Yes" button on "Do you want to map geographic data to grid attributes now?" dialog, the polygon of roughness is not mapped to grid.

The reason was that "Multifunction Grid Generator" outputs attributes values of "Elevation", "Fixed or Movable Bed" and "Manning's roughness coefficient". With "Multifunction Grid Generator", user can specify bed condition and roughness value from "Bed Condition" page, like below.

![screenshot](https://user-images.githubusercontent.com/4031569/77491921-6c4cd580-6e82-11ea-8863-8805d7a46c94.png)

When grid attribute value is output by grid generator, iRIC does not overwrite it, and map the others only.

You can check that the other grid attributes, like "Obstacle", "Density of Vegetation (m-1)" are mapped, with issue-694.ipro attached below.

[issue-694.zip](https://github.com/i-RIC/prepost-gui/files/4378503/issue-694.zip)

I think that basically it is a right behavior that iRIC avoids overwriting grid attributes values output by grid generator by default, but sometimes confusing, as we've experienced recently.

## Draft idea about how to close this issue

My idea is like below.

When grid generator outputs grid attributes, and some geographic data exists for that attributes, a dialog with following message will be shown after mapping is executed.

> The following attributes were not mapped, because grid generator output values for them. If you want to map geographic data for them forcibly, please map manually with menu "Grid" -> "Attributes Mapping" -> "Execute".
> * Elevation (m)
> * Fixed or Movable Bed
> * Manning's roughness coefficient

I guess that with this message, user can avoid being confused.

It is just an idea, and I welcome comments or ideas about improvements.

I also think that maybe we can ask developer of "Multifunction grid generator"
to disable outputting roughness, when "Roughness Definition" is "Not Specified". This fix will also help to reduce the occurrence of the confusing situations.

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I'm still a little confused.  When will you show the new dialog that starts with "The following attributes were not mapped, ..."  and does this dialog replace the current dialog that asks "Do you want to map geographic data to grid attributes now."?  Or is the new dialog shown only if the uses answers yes to the old dialog?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your response.
Yeah, it is a little confusing. I'm sorry.

To make it clear, I've written some code to let you understand what I mean. It is a draft code, so maybe I will make fixes before making a pull request. I hope it will help us communicate.

https://github.com/kskinoue0612/prepost-gui/tree/issue-694-draft

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I don't think I got notified of your latest comment.  Now I understand how it's intended to be used.  I think it's good the way you implemented it.  Go ahead and merge if you think it's OK.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your comment.
OK. I'll check again, modify Japanese dictionary, and merge it.

Thank you.
Keisuke
