### ISSUE TITLE
iRIC 2.3 Polygon filling takes much time when importing many polygons

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#7]
When user import many polygons (for example, 1,500) from ESRI Shape files, it take so much time
before all polygons are shown as filled polygons.

**Comment by kazutake** [comment]
Above problem was cleared on v2.3.11.6382 . But , iRIC is crashed when it is reading the attached 01_yugou_h=10.0.shp file.






[shp_edit.zip](https://github.com/i-RIC/prepost-gui/files/547144/shp_edit.zip)

**Comment by kskinoue0612** [comment]
OK, I will check it when I am back to Japan.

**Comment by kskinoue0612** [comment]
Please close this issue, because the crash problem you've reported is registered as a separate issue, #19.

**Comment by kazutake** [comment]
OK
