### ISSUE TITLE
Port iRIC GUI to Linux

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#73]
Port iRIC GUI into linux distributions.

**Comment by kskinoue0612** [comment]
Porting is almost done already, but still have issues:
* Testing is not enough
* No installer prepared

**Comment by kazutake** [comment]
????

**Comment by scharlton2** [comment]
Compiles and links cleanly on Ubuntu 16.04.3 using https://github.com/scharlton2/prepost-gui/tree/ubuntu_16.04.3 which is a rebase/squash of _ubuntu_16.04.3.
