### ISSUE TITLE
Replace 32-bit zip.exe and unzip.exe with 64-bit versions.

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#732]
Hi Keisuke,

I looked around and couldn't find a pre-built 64-bit version of zip.exe.  Nor could I find source code.  I think that I once heard that creating zip files is proprietary while unzip(ing) them is not.

I think that we should use 7-zip.  Their Developer FAQ ([https://www.7-zip.org/faq.html](https://www.7-zip.org/faq.html#developer_faq)) states that it can be used in a commercial application as long as we follow a few requirements.

1. Document usage
2. Document GNU LGPL license
3. Give source code link to www.7-zip.org.

Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I did finally find this:
[http://infozip.sourceforge.net/Zip.html](http://infozip.sourceforge.net/Zip.html)

here is a x64 compiled version:
[ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn-x64.zip](ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn-x64.zip)

Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I assigned this to myself since I'm almost finished with it.  I just need to test it some more.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

OK, thank you!

2020年6月15日(月) 11:04 Scott Charlton <notifications@github.com>:
