### ISSUE TITLE
Removing calculation results crashes iRIC

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#734]
Opening ptk2018trsynksource.7z from:

https://drive.google.com/drive/folders/1aZzQ1MYpmfFfQfKymQaMjwqVREYQAmCO?usp=sharing

with the [utt.zip](https://github.com/i-RIC/prepost-gui/files/4776724/utt.zip) solver crashes when selecting "Calculation Result->Delete...".

Doesn't crash in [iRIC_dev 3.0.18.6272](https://ci.appveyor.com/api/buildjobs/o7g7ou7r4s5ndv9s/artifacts/iRIC_Installer_190926_87ab1237.exe).

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you reporting the issue.
Reviewing the list of issues, I've noticed that this issue is the same to #758.

I've made sure that this issue is fixed with develop branch, so I close
this.

Thanks,

Keisuke
