### ISSUE TITLE
Refactor code so that it is easy to run automated test for various GUI functions

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#774]
Currently tests are run manually, but it is time consuming, and not easy to run every time.

Maybe it will be partial, but refactor code to run automated test for GUI functions.
At first step it may be enough to load various project files, run models, and open chart windows and visualization windows.

**Comment by kazutake** [comment]
Do you have any idea to test the code or to make it automate?

**Comment by kazutake** [comment]
Implementation of the CUI functions should be first.
