### ISSUE TITLE
River survey data is imported from reverse order when loaded with non-number cross-section names

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#84]
River survey data used to have limitation that cross section names have to be real numbers, like "2.0", "2.5".

Now the limitation is gone and user can specify string names. but in that case, it is assumed that the cross-sections defined in river survey data are ordered from upstream to downstream. And, that is the reverse order to the files that are already created.

We should reverse the order when loading river survey data with "String" cross-section names.

**Comment by kazutake** [comment]
Please write down this into the user's manual.

**Comment by kazutake** [comment]
Check the relationship between the riv file format and the drawing logic.

**Comment by kskinoue0612** [comment]
Hi Kazutake,

I've checked how the cross-section are ordered when cross-sections with non-decimal names exists in *.riv file.

When all names are decimal, like "2.0", "3.0", "4.0", ..., the cross-sections with smaller values are recognized to be downstream. But if it contains non-decimal names, the cross-sections that appears earlier in *.riv files are recognized to be upstream.

It is a problem because when user accidentally make the name value non-decimal, like "3.0-dash", the order suddenly becomes reversed.

To make the behavior fixed, I think I should make the order with *.riv file with non-decimal names the reverse.
