### ISSUE TITLE
Post2D window "Contour Figure" drawing has memory leak

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#85]
Post2D window "Contour Fringe" has memory leak. When user changes scalar setting and redraw contour figures, 20 MB or larger memory is consumed (The leaked memory size depends on the size of grid) every time.

**Comment by kskinoue0612** [comment]
Please use the attached file to test this.

[result.zip](https://github.com/i-RIC/prepost-gui/files/1104038/result.zip)

**Comment by kazutake** [comment]
OK
