### ISSUE TITLE
Add function to map polylines to grid cells and grid nodes.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#852]
# Nodes
polylines are mapped to nodes where the polyline crosses the edges.

# Cells

polyline are mapped to cells where the polyline passes.

![mapping](https://user-images.githubusercontent.com/4031569/103165526-6a260600-485c-11eb-9e13-48dfb6f448c7.png)

**Comment by scharlton2** [comment]
Hi Keisuke,

What about when a line crosses at a node (or ends on a node)?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the comment.

> What about when a line crosses at a node (or ends on a node)?

I've made sure about above.

For attributes defined at nodes, iRIC map to node if a polyline "crosses" the edge that includes the node.

And if the polyline crosses an edge or not is calculated with GeoDataPolyLineGroupPolyLine::intersectWithLine(), that is implemented with the following commit:

https://github.com/i-RIC/prepost-gui/pull/860/commits/84f9573eea0b5554d94e539e24aa21256709fe2b

Reading the code, it returns true, when 0 <= r <= 1, and 0 <= t <= 1.

r = 0, r = 1 means that the polyline crosses at a node (or ends on a node), so the polyline will be mapped to the node.

I've created a sample project issue-852_2.zip, and attached below. As expected, if a polyline ends on node, that is mapped to the node. Please try with 10dab2f876035f82fd31a0a61a0042fc7377ad0c.

[issue-852_2.zip](https://github.com/i-RIC/prepost-gui/files/5792318/issue-852_2.zip)

Thanks,

Keisuke

**Comment by scharlton2** [comment]
Hi Keiskuke,

Thanks for your detailed response.  Sorry, I should have been more explicit in my question.  When a line crosses or ends on a node which nodes do you apply the value to?

For example:

![image](https://user-images.githubusercontent.com/7538707/104144355-1c42ef00-5380-11eb-8b65-de1e1fd9dd7b.png)

If the blue cell is intersected (or is an end point) which of the green cells does it apply?  Does it matter how close the adjacent nodes are? (If delta x is greater than delta y?)

Thanks,
Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I did some testing and it looks like all green cells are set (regardless of different deltas). I hope you had a good Coming of Age Day.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

> Hi Keisuke,
> 
> I did some testing and it looks like all green cells are set (regardless of different deltas).


Thank you for testing. Yes, you are right, currently all green cells are set. Maybe users hope that if the delta is very small, the line is mapped to blue point only. In that case, we will make another issue, and change the behavior.

> I hope you had a good Coming of Age Day.

Thank you! We had!

Keisuke
