### ISSUE TITLE
Add function to use pens with tablets to draw polygon etc.

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#856]
Recently, tablets with pens are becoming popular, like Surface from Microsoft.
With Qt, we can implement tablet related operation using tabletEvent().

https://doc.qt.io/qt-5/qwidget.html#tabletEvent

Implement tabletEvent handlers so that we can define or edit polygons, polylines, grid center lines, etc.

**Comment by kazutake** [comment]
It is good for users if it will come into the iRIC software. But more voice of user would be required.
