### ISSUE TITLE
RivMaker 2.0 crashes when opening a file

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#858]
Version:

![image](https://user-images.githubusercontent.com/7538707/103961159-1dbab000-5111-11eb-8244-e782bbf9cc7d.png)

Steps to reproduce:
1. Open RivMaker 2.0
2. File->Import->Geographic Data-> SAC GUI Input File... and choose 'example_xs.csv'
3. File->Open...
4. Answer 'No' to the Warning Message: 

![image](https://user-images.githubusercontent.com/7538707/103961555-f31d2700-5111-11eb-8d39-cba1ad9ca5ec.png)

**Comment by scharlton2** [comment]
I forgot to include the import file:

[example_xs.zip](https://github.com/i-RIC/prepost-gui/files/5784637/example_xs.zip)

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for the information. I've tested, and it seems that the bug exists in all versions or RivMaker, including 1.0.
I'll try to fix this.

Thanks,

Keisuke
