### ISSUE TITLE
Poisson Equation grid generator mouse operation bug

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#86]
In poisson equation grid generator, it is hard to "grab" the starting point or end point of control cross sections.
Reported by Kazutake.

**Comment by kskinoue0612** [comment]
I've tested, but it seems to me that grabbing the starting point or end point is not hard.

**Comment by kazutake** [comment]
Did you try to grab the edge's points of upstream and downstream edges?

**Comment by kskinoue0612** [comment]
This is fixed by closing issue #215.
Now drag radius is 10 pixels.
