### ISSUE TITLE
Add function to import and export center line of river survey data

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#885]
Export center line of river survey data as *.shp file.
When importing, by specifying the *.shp file, we can import center line correctly.

**Comment by scharlton2** [comment]
Hi Keisuke,

I reopened this since your comment was about exporting shape files and #892 was about exporting csv files.  You can re-close if you're okay with it.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your notification.

When I registered this issue, we planned to add function to export shape files. But in a discussion with customers, we decided that we export CSV files instead of shape files, because they are easy to edit for many users. So, it is OK.

I re-close this issue.

Thank you,

Keisuke
