### ISSUE TITLE
Post2D window Streamline drawing has memory leak

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#89]
Post2D window Streamline has memory leak. When user setup Streamline drawing setting, and changes time step to draw, 20 MB or larger memory is consumed (The leaked memory size depends on the number and the lengths of streamlines) every time.

**Comment by kskinoue0612** [comment]
Fixed in 3.0.0.6198.

Please use the result.zip to test this, that is attached to https://github.com/i-RIC/prepost-gui/issues/85

**Comment by kazutake** [comment]
OK
