### ISSUE TITLE
iRIC 2.3 project file saving fails when there are so many geographic data

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#9]
Saving project file to *.ipro file fails (never ends) when there are so many geographic data (for example after importing 1,500 polygons).

**Comment by kazutake** [comment]
Above problem was cleared on v2.3.11.6382 .

**Comment by kazutake** [comment]
iRIC will be crashed when you try following procedure

1. Start Nays2DH
2. import attached file polygons for "植生高さ(m)"
3. Select Name for Name and Value for Value
4. Click OK

[Uploading shape_for_11.zip…]()

**Comment by kazutake** [comment]
OK. I confirmed above problem is cleared.
