### ISSUE TITLE
Tin mapping is very slow in 3.0, compared to 2.3

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#90]
When using TIN data with million points, TIN mapping to grid takes several minutes in version 2.3, but in 3.0, it does not finish after one hour.

**Comment by kazutake** [comment]
Please tell the status.

**Comment by kskinoue0612** [comment]
Rich and I had a discussion, and think that maybe we add an option for search algorithm.
In data with good triangles, we can adopt more simple algorithm to find the triangle, and it
will make the mapping much faster.

**Comment by kskinoue0612** [comment]
We are going check if the grid node is inside bounding box of the whole TIN.
