### ISSUE TITLE
Geographic data grouping

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#922]
Now geographic data is listed like below:

* Elevation
* Obstacle
* Manning's roughness
* Reference Information

Change this to like below:
* Node attributes
    * Elevation
* Cell attributes
    * Obstacle
    * Manning's roughness
* Reference Information

**Comment by kazutake** [comment]
It is good for users if it will come into the iRIC software. But more voice of user would be required.
