### ISSUE TITLE
Add function to edit solver execution environment

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/prepost-gui#953]
Add function to edit solver execution environment
For example, with Visual Studio Code, we can edit setting with settings.json. We image function similar to that.

For example, environmental variables like:
* OMP_NUM_THREADS
* IRIC_SEPARATE_RESULTS

They will be stored to project files.

**Comment by kazutake** [comment]
It is good for users if it will come into the iRIC software. But more voice of user would be required.
