### ISSUE TITLE
Post only mode can not be saved as its project file.

### ISSUE THREAD

**Issue by kazutake** [i-RIC/prepost-gui#98]
iRIC v3 can import and visualize a CGN file including calculation results which are produced by a solver without definition.xml. But the file cannot be saved as both an ipro file and a project folder.

**Comment by kskinoue0612** [comment]
This issue can be tested in the way below:

1. Create a new project, run model, and saves the project file.
2. Temporary move the solver from the "solvers" folder to somewhere
3. Open the project file again. Now the project is in "Post Only" mode.
4. Opens Post2D window, chart window etc. and visualize result.
5. Make sure that you can save the project, and can open the project file to restore the visualization windows.
